/**
 * rootCaCert.ts
 * Root CA сертификат — генериран от scripts/generate-root-ca.mjs
 * Публичен: може да се commit-ва в repo.
 * Ползва се при Фаза 5 (верификация на подпис).
 */
export const ROOT_CA_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIIBqTCCAU6gAwIBAgIQGXiaUYIJsKprlA/xSk3J6zAKBggqhkjOPQQDAjBCMR4w
HAYDVQQDExVTaWduU2hpZWxkIFJvb3QgQ0EgdjExEzARBgNVBAoTClNpZ25TaGll
bGQxCzAJBgNVBAYTAkJHMB4XDTI2MDgxMTEyNDA0OFoXDTM2MDgxMTAwNDA0OFow
QjEeMBwGA1UEAxMVU2lnblNoaWVsZCBSb290IENBIHYxMRMwEQYDVQQKEwpTaWdu
U2hpZWxkMQswCQYDVQQGEwJCRzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIJQ
UBPRuVMHx8CW/gNXVmzdn4HDjfBEnV328FM4wfEG5jOMOdBIlMWA0aGm6BMI/1nr
f4L0INWky9pFMuwcXQOjJjAkMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/
BAQDAgEGMAoGCCqGSM49BAMCA0kAMEYCIQCeh1ncStGqs+ctnut9BxfXMf1mo5zs
IXWx5dXPoKXG1QIhAI64uGhuOpRVaZy9/wUq0zLr+f7Z68FzTn4GYeZKFaHY
-----END CERTIFICATE-----`;
